---
title: "Oblig1c.Rmd"
author: "Inge Johan Johansson"
date: "`r Sys.Date()`" 
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(alr4)
```

## R Markdown
Eg har gjort R basic.



## Including Plots

#You can also embed plots, for example:

#```{r pressure, echo=FALSE}
#plot(pressure)
#```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

Oppgave 3: Produser dataene fra oblig 1 i en PDF.

```{r data_kvit}
data_kvit <- read.csv("rosa_kvit42.csv")
data_groon <- read.csv("rosa_groon42.csv")

head(data_kvit[, c("Lower", "Upper")], 31)
head(data_groon[, c("Lower", "Upper")], 31)
```


Oppgave 4: 
```{r regression_model}
# read.csv funksjon oppgave 1b. Leser Terning_20.csv
data_terning <- read.csv("Terning_20.csv")

# Regresjons linje
regression_model <- lm(Lengde ~ Hoyde, data = data_terning)

summary(regression_model)

# Plotter splatterplot og regresjons linje
plot(data_terning$Hoyde, data_terning$Lengde, main = "Lengde vs Hoyde", xlab = "Hoyde", ylab = "Lengde", pch = 19)
abline(regression_model, col = "red")
```

``` {r fuel2001}
head(fuel2001)
write.csv(fuel2001, "fuel2001.csv")
```




Oppgave 24 kapittel4

```{r oppgave 24 kapittel 4}
# A)
# Antall elementer å velge fra
n <- 12

# Antall valg som skal gjøres
r <- 5

# Beregn antall måter ved å heve n til r's potens
antall_måter <- n^r

print(antall_måter)


# B)
# Antall elementer å velge fra
n <- 12

# Antall valg som skal gjøres
r <- 5

# Beregn kombinasjoner med repetisjon ved hjelp av choose-funksjonen
kombinasjoner <- choose(n + r - 1, r)

print(kombinasjoner)

# C)
# Antall elementer å velge fra
n <- 12

# Antall valg som skal gjøres
r <- 5

# Beregn permutasjoner uten tilbakelegging
permutasjoner <- factorial(n) / factorial(n - r)

print(permutasjoner)



# D)
# Antall elementer å velge fra
n <- 12

# Antall valg som skal gjøres
r <- 5

# Beregn kombinasjoner uten tilbakelegging ved hjelp av choose-funksjonen
kombinasjoner <- choose(n, r)

print(kombinasjoner)


# E)
#Ordnet med tilbakelegging (Lås med fem-sifret kode):
#Her kan hvert siffer være mellom 0 og 11, og sifre kan gjentas
n <- 12  # 12 mulige sifre (0-11)
r <- 5   # 5 sifre i koden
mulige_kombinasjoner <- n^r
print(mulige_kombinasjoner)

#Ordnet uten tilbakelegging (Top 5 plasseringer i et løp med 12 deltakere)
#Her kan en løper ikke inneha mer enn en av de topp 5 plasseringene.
n <- 12  # 12 deltakere
r <- 5   # Topp 5 plasseringer
mulige_perumtasjoner <- factorial(n) / factorial(n - r)
print(mulige_perumtasjoner)

#Uordnet med tilbakelegging (Fruktsalat med 5 frukter valgt fra 12 mulige):
#Her kan samme frukt velges flere ganger, men rekkefølgen betyr ingenting.
n <- 12  # 12 forskjellige frukter
r <- 5   # 5 frukter i salaten
mulige_kombinasjoner <- choose(n + r - 1, r)
print(mulige_kombinasjoner)


#Uordnet uten tilbakelegging (Fruktkurv med 5 frukter valgt fra 12 mulige):
#Her er det bare en av samme frukt, men rekkefølgen betyr ingenting.
n <- 12  # 12 mulige gaver
r <- 5   # 5 unike gaver i kurven
mulige_kombinasjoner <- choose(n, r)
print(mulige_kombinasjoner)


```
Oppgave 15 og 16 kapittel 5
```{r oppgave 15 og 16 kapittel 5} 
# Definerer sannsynligheter
p <- 0.37  # Sannsynlighet for M (mynt)
q <- 1 - p  # Sannsynlighet for K (kron)

# Antall M og K i sekvensen
antall_M <- 14
antall_K <- 10  # Justert total antall basert på sekvenslengde minus antall M

# Beregner sannsynligheten for sekvensen
sannsynlighet_sekvens <- (p^antall_M) * (q^antall_K)

# Skriver ut sannsynligheten
print(sannsynlighet_sekvens)


# Parametre
n <- 37  # Totalt antall kast
k <- 14  # Antall ønskede suksesser (M)
p <- 0.37  # Sannsynlighet for M

# Binomisk sannsynlighet
sannsynlighet <- dbinom(k, n, p)

print(sannsynlighet)



```
